1 to: 100000 do: 
[ :i |
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
    extern := nil.
]
